# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: karsajobs-ci

on:
    push:
        branches:
            - karsajobs
    workflow_dispatch:
    pull_request:

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.15'
        
    - name: lint-dockerfile
      run: |
        sudo apt update && sudo apt install shellcheck -y
        wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
        sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
        sudo chmod u+x /usr/local/bin/hadolint
        hadolint Dockerfile
        
    - name: test-app
      run: go test -v -short --count=1 $(go list ./...)

    - name: build-app-karsajobs
      # You may pin to the exact commit or the version.
      # uses: GlueOps/github-actions-build-push-containers@4ae580f710f614ccba941103be98dc97db6599b3
      uses: macbre/push-to-ghcr@v13
      with:
        # Your secrets.GITHUB_TOKEN
        github_token: ${{ github.token }}
        # Image name, e.g. my-user-name/my-repo (will be lowercased)
        image_name: farraselfahd/karsajobs
        # A path to the Dockerfile (if it's not in the repository's root directory)
        dockerfile: ./Dockerfile
        # A path to the context in which the build will happen, see https://docs.docker.com/engine/reference/commandline/build/
        context: .
        # Docker repository to push an image to, defaults to ghcr.io
        repository: ghcr.io
        # A username to use when pushing an image to docker.io (defaults to the github.actor)
        #docker_io_user: # optional
        # Your docker.io token created via https://hub.docker.com/settings/security
        #docker_io_token: # optional
        # Image tag, e.g. latest. Will overwrite the tag latest tag on a push, and have no effect on a release.
        image_tag: latest
